name: device_meta_example
description: Demonstrates how to use Device meta.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_meta:
    path: ../

flutter:

  uses-material-design: true