name: device_meta
description: "Basic information about the user's device. Fetch the device's model, manufacturer, operating system, version and more."
version: 1.1.29
homepage: https://nylo.dev
repository: https://github.com/nylo-core/device_meta
funding:
  - https://github.com/sponsors/agordn52
topics:
  - device-info
  - device-meta
  - operating-system

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  nylo_support: ^5.76.0
  flutter:
    sdk: flutter
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:


